### ISSUE TITLE
Unexpected behavior: TODOUNDATED ignores Daily Notes

### ISSUE THREAD

**Issue by tbastos** [dvargas92495/roamjs-smartblocks#44]
`TODOUNDATED` finds undated TODOs in normal pages, but not in Daily Notes. This is unexpected, as the documentation says:

> Purpose: Returns a list of block references of TODOs with no date

Without any qualification, I'd expect it to work for TODOs in Daily Notes. Lots of people create tasks in their Daily Notes by default, and without `TODOUNDATED` we cannot detect when we forgot to schedule a TODO, and it may be lost forever.

For example, I have the following in my Daily SmartBlock:
```
- <%TODOTODAY%><%SKIPIFEMPTY%>
- ### <%IFCHILDREN%>📥 Inbox (unscheduled)
    - <%TODOUNDATED:20,(({uid})),-Now,-Soon,-Later%><%SKIPIFEMPTY%>
- ### <%IFCHILDREN%>⏰ Overdue
    - <%TODOOVERDUE%><%SKIPIFEMPTY%>
- ### <%IFCHILDREN%>🔜 Upcoming
    - <%TODOFUTUREDNP%><%SKIPIFEMPTY%>
```

This would work almost perfectly to ensure I don't miss any tasks (and that they're all tagged with a date or with Now/Soon/Later) if `TODOUNDATED` worked with Daily Notes.

Is there any reason why we can't have this feature?

**Comment by dvargas92495** [comment]
This is intentional, and I have updated the docs to clarify so. There are several users dependent on "dated" to mean either tagged by dates or on a date page.

I would recommend checking out `TODOOVERDUEDNP` to see if it covers the rest of your needs. If not, I'm open to PRs for a new command that is similar to TODOUNDATED but achieves what you're looking for
