### ISSUE TITLE
button trigger should support sibling output

### ISSUE THREAD

**Issue by dvargas92495** [dvargas92495/roamjs-smartblocks#65]
let's allow both previous and next sibling

let's also allow "output nowhere"

**Comment by mdroidian** [comment]
Looking at the possible combinations between `RemoveButton`, `Clear`, and `Sibling` has been interesting.

Clear is currently undocumented.  Is that by design?  Or should I cover all combinations?

Also, as `RemoveButton` applies to child, it seems that we wouldn't have the use case of "Keep Button and apply to current block" covered.

**Comment by dvargas92495** [comment]
If there's anything in the code that isn't documented, assume that's a gap in the documentation.

I don't think there is a use case for `"Keep Button and apply to current block" covered.`

**Comment by mdroidian** [comment]
Docs updated in roam graph.
